### ISSUE TITLE
Sentinel 2 Cloud Masking 

### ISSUE THREAD

**Issue by MrZombie69232** [ceos-seo/odc-colab#5]
Hi,
Isn't there a way to clean or apply cloud masking on sentinel image ?
sentinel2_fmask_clean_mask doesn't seems to work even .

Thank you !

**Comment by MrZombie69232** [comment]
Hi @dlubawy-ama ,
can you please help me with this?
Thanks & Regards
Satyam

**Comment by dlubawy-ama** [comment]
Hi @MrZombie69232,
Sorry for the late response. The utility in question was based on a specific Sentinel-2 product used elsewhere that had an fmask band. However, the GEE Sentinel-2 data uses a different band named SCL that is different but which provides equivalent cloud masking functionality. So, that util will not work with the GEE product in our Colab environment, but it could be modified to perform the same function.

With that said, there is work being done to improve the ODC-GEE products. One improvement is in better defining 'flags_definition' in the product definition. This would allow for the use of [ODC masking functions](http://web.archive.org/web/20200803180648/https://datacube-core.readthedocs.io/en/latest/dev/api/masking.html) which wouldn't rely on hardcoded values like that fmask util.
